server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/RomanticCloud/SpringCloud.git