server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002
  client:
    register-with-eureka: false #表示是否向注册中心注册自己
    fetch-registry: false #false表示自己是注册中心
    service-url:
      defaultZone: http://eureka7001:7001/eureka/