server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false #表示是否向注册中心注册自己
    fetch-registry: false #false表示自己是注册中心
    service-url:
      defaultZone: http://eureka7002:7002/eureka/